TYPE_PLAYLIST = 'PLAYLIST'
TYPE_ALBUM = 'ALBUM'
TYPES = [TYPE_PLAYLIST, TYPE_ALBUM]
ORG_SPOTIFY = 'SPOTIFY'
ORG_YOUTUBE = 'YOUTUBE'
ORGS = [ORG_SPOTIFY, ORG_YOUTUBE]

ARTISTS_FILENAME = 'artists.csv'
MEDIA_ITEMS_FILENAME = 'media_items.csv'
MEDIA_ITEM_METADATA_FILENAME = 'media_item_metadata.csv'
PLAYLIST_METADATA_LOG_FILENAME = 'playlist_metadata_log.csv'
PLAYLIST_PLAYS_LOG_FILENAME = 'playlist_plays_log.csv'
PLAYLIST_POSITIONS_LOG_FILENAME = 'playlist_positions_log.csv'
PLAYLISTS_FILENAME = 'playlists.csv'
USERS_FILENAME = 'users.csv'
